/*
 * Anna Vilanova: Basic user interface for the raycaster. NO MODIFICATION NEEDED 
 *
 *
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tudelft.cgv.gui;

import java.awt.BorderLayout;
import tudelft.cgv.volvis.RaycastRenderer;
import javax.swing.JColorChooser;
import java.awt.Color;
import tudelft.cgv.volvis.TFColor;

/**
 *
 * @author michel
 */
public class RaycastRendererPanel extends javax.swing.JPanel {

    RaycastRenderer renderer;
    TransferFunctionEditor tfEditor = null;
    TransferFunction2DEditor tfEditor2D = null;
    
    /**
     * Creates new form RaycastRendererPanel
     */
    public RaycastRendererPanel(RaycastRenderer renderer) {
        initComponents();
        this.renderer = renderer;
        IsovalueTextBox.setText(Float.toString(renderer.getIsoValue()));
        colorButton.setBackground(new Color(255,255,0));
    }

    public void setSpeedLabel(String text) {
        renderingSpeedLabel.setText(text);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        renderingSpeedLabel = new javax.swing.JLabel();
        slicerButton = new javax.swing.JRadioButton();
        mipButton = new javax.swing.JRadioButton();
        compositingButton = new javax.swing.JRadioButton();
        tf2dButton = new javax.swing.JRadioButton();
        shadingCheckbox = new javax.swing.JCheckBox();
        IsoSurface = new javax.swing.JRadioButton();
        IsovalueTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Resolution = new javax.swing.JSlider();
        Resolution_label = new javax.swing.JLabel();
        colorButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        boundaryEnhancement = new javax.swing.JRadioButton();
        surfaceEnhancement = new javax.swing.JRadioButton();
        defaultShading = new javax.swing.JRadioButton();
        toneShading = new javax.swing.JRadioButton();

        jLabel1.setText("Rendering time (ms):");

        renderingSpeedLabel.setText("jLabel2");

        buttonGroup1.add(slicerButton);
        slicerButton.setSelected(true);
        slicerButton.setText("Slicer");
        slicerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slicerButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(mipButton);
        mipButton.setText("MIP");
        mipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mipButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(compositingButton);
        compositingButton.setText("Compositing");
        compositingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compositingButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(tf2dButton);
        tf2dButton.setText("2D Transfer function");
        tf2dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2dButtonActionPerformed(evt);
            }
        });

        shadingCheckbox.setText("Shading");
        shadingCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shadingCheckboxActionPerformed(evt);
            }
        });

        buttonGroup1.add(IsoSurface);
        IsoSurface.setText("IsoSurface Rendering");
        IsoSurface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsoSurfaceActionPerformed(evt);
            }
        });

        IsovalueTextBox.setText("0");
        IsovalueTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IsovalueTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsovalueTextBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Isovalue:");

        Resolution.setMajorTickSpacing(1);
        Resolution.setMaximum(4);
        Resolution.setMinimum(1);
        Resolution.setMinorTickSpacing(1);
        Resolution.setPaintLabels(true);
        Resolution.setPaintTicks(true);
        Resolution.setSnapToTicks(true);
        Resolution.setToolTipText("");
        Resolution.setValue(1);
        Resolution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ResolutionMouseReleased(evt);
            }
        });

        Resolution_label.setText("Resolution");

        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Color");

        buttonGroup2.add(boundaryEnhancement);
        boundaryEnhancement.setText("Boundary Enhancement");
        boundaryEnhancement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boundaryEnhancementActionPerformed(evt);
            }
        });

        buttonGroup2.add(surfaceEnhancement);
        surfaceEnhancement.setText("Surface Enhancement");
        surfaceEnhancement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surfaceEnhancementActionPerformed(evt);
            }
        });

        buttonGroup2.add(defaultShading);
        defaultShading.setText("Basic Volume Shading");
        defaultShading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultShadingActionPerformed(evt);
            }
        });

        buttonGroup2.add(toneShading);
        toneShading.setText("Tone Shading");
        toneShading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toneShadingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(renderingSpeedLabel)
                        .addGap(304, 304, 304))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(compositingButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf2dButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mipButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slicerButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(IsoSurface)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IsovalueTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(colorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Resolution_label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Resolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toneShading)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(shadingCheckbox)
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(surfaceEnhancement)
                                            .addComponent(boundaryEnhancement)
                                            .addComponent(defaultShading))))))
                        .addGap(0, 115, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(renderingSpeedLabel))
                .addGap(49, 49, 49)
                .addComponent(slicerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mipButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IsoSurface)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IsovalueTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compositingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2dButton)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boundaryEnhancement, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shadingCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(surfaceEnhancement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(defaultShading)
                .addGap(2, 2, 2)
                .addComponent(toneShading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Resolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resolution_label))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void mipButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        renderer.setMIPMode();
    }                                         

    private void slicerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        renderer.setSlicerMode();
    }                                            

    private void compositingButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        renderer.setCompositingMode();
    }                                                 

    private void tf2dButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        renderer.setTF2DMode();
    }                                          

    private void shadingCheckboxActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if (shadingCheckbox.isSelected() == false){
            boundaryEnhancement.setSelected(false);
            surfaceEnhancement.setSelected(false);
            defaultShading.setSelected(false);
            renderer.setTotalShadingMode(false, false, "Default");
        }
        else{
            defaultShading.setSelected(true);
            renderer.setTotalShadingMode(true, false, "Default");
        }

    }                                               

    private void IsoSurfaceActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        renderer.setIsoSurfaceMode();
    }                                          

    private void IsovalueTextBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        String s=this.IsovalueTextBox.getText();
        renderer.setIsoValue(Float.parseFloat(s));//set value
    }                                               

    private void ResolutionMouseReleased(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        renderer.setResFactor(this.Resolution.getValue());
    }                                        

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // Change the color in the transfer function.
        Color newColor = JColorChooser.showDialog(this, "Choose color", colorButton.getBackground());
        if (newColor != null) {
            colorButton.setBackground(newColor);
            TFColor isoColor=new TFColor();
            isoColor.r = newColor.getRed() / 255.0;
            isoColor.g = newColor.getGreen() / 255.0;
            isoColor.b = newColor.getBlue() / 255.0;
            renderer.setIsoColor(isoColor);
        }
    }                                           

    private void boundaryEnhancementActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        renderer.setShadingMode(shadingCheckbox.isSelected(), "Boundary");
    }                                                   

    private void surfaceEnhancementActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        renderer.setShadingMode(shadingCheckbox.isSelected(), "Surface");
    }                                                  

    private void defaultShadingActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        renderer.setShadingMode(shadingCheckbox.isSelected(), "Default");
    }                                              

    private void toneShadingActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        shadingCheckbox.setSelected(false);
        renderer.setTotalShadingMode(false, true, "Default");
    }                                           

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton IsoSurface;
    private javax.swing.JTextField IsovalueTextBox;
    private javax.swing.JSlider Resolution;
    private javax.swing.JLabel Resolution_label;
    private javax.swing.JRadioButton boundaryEnhancement;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton colorButton;
    private javax.swing.JRadioButton compositingButton;
    private javax.swing.JRadioButton defaultShading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton mipButton;
    private javax.swing.JLabel renderingSpeedLabel;
    private javax.swing.JCheckBox shadingCheckbox;
    private javax.swing.JRadioButton slicerButton;
    private javax.swing.JRadioButton surfaceEnhancement;
    private javax.swing.JRadioButton tf2dButton;
    private javax.swing.JRadioButton toneShading;
    // End of variables declaration                   
}
